# Generated by Django 4.2.4 on 2023-10-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_contact_contactform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='phone',
        ),
        migrations.AddField(
            model_name='contactform',
            name='message',
            field=models.TextField(default='Default Message'),
        ),
    ]
