# Generated by Django 4.2.4 on 2023-10-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_medicinelib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinelib',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medicine'),
        ),
    ]
