# Generated by Django 4.2.4 on 2023-10-10 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_medicinelib_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicinelib',
            old_name='uses',
            new_name='side_effects',
        ),
    ]
