# Generated by Django 4.2.4 on 2023-10-10 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_medicinelib_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'ordering': ['name']},
        ),
    ]
