# Generated by Django 4.2.4 on 2023-10-16 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_medicinedetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='medicinedetails',
            new_name='medicine_detail',
        ),
    ]
