# Generated by Django 4.2.5 on 2023-10-20 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_appointmentsform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentsform',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='appointmentsform',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='appointmentsform',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
