# Generated by Django 4.2.5 on 2023-10-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_email_address_appointmentsform_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentsform',
            name='date',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='appointmentsform',
            name='time',
            field=models.TextField(default=''),
        ),
    ]
