# Generated by Django 4.2.4 on 2023-10-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_room_delete_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='{{ room.room_number }}'),
        ),
    ]
