# Generated by Django 4.2.4 on 2023-10-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_room_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
        migrations.AddField(
            model_name='room',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='roomy'),
        ),
    ]
