# Generated by Django 4.2.4 on 2023-10-21 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_room_image_room_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='image_url',
            new_name='image',
        ),
    ]
