# Generated by Django 4.2.4 on 2023-10-26 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_image_url_room_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='dosageform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosageform', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['dosageform'],
            },
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='roompic'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AddField(
            model_name='medicinelib',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dosageform'),
        ),
    ]
