# Generated by Django 4.2.4 on 2023-10-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_dosageform_alter_room_image_alter_room_room_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dosageform',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='dosageform',
            old_name='dosageform',
            new_name='name',
        ),
    ]
