# Generated by Django 4.2.5 on 2023-10-27 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_category_remove_medicinelib_form_delete_dosageform_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentsform',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointmentsform',
            name='room',
        ),
        migrations.RemoveField(
            model_name='medicinelib',
            name='categories',
        ),
        migrations.DeleteModel(
            name='category',
        ),
    ]
