# Generated by Django 4.2.4 on 2023-10-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_appointmentsform_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentsform',
            name='doctor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
