# Generated by Django 4.2.5 on 2023-10-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_appointmentsform_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentsform',
            name='room',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
