# Generated by Django 4.2.5 on 2023-10-28 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_appointmentsform_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['room_number']},
        ),
    ]
